{
 "title": "Huma grafana dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", namespace=\"$namespace\"}, persistentvolumeclaim)"
   },
   { "name": "interval", "query": "4h" },
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   {
    "name": "disknode",
    "query": "label_values(node_exporter_build_info, instance)"
   },
   {
    "name": "ingress",
    "label": "Service Ingress",
    "query": "label_values(nginx_ingress_controller_requests, ingress) "
   }
  ]
 },
 "panels": [
  {
   "title": "Response error volume by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum (\n    rate(\n      nginx_ingress_controller_request_duration_seconds_count{\n        ingress =~ \"$ingress\",\n        status =~\"[4-5].*\",\n      }[1m]\n    )\n  ) by(path, status)",
     "legendFormat": "{{ path }} {{ status }}"
    }
   ]
  },
  {
   "title": "Checking default namespace pod running errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{namespace=\"default\"}) by (reason,pod,default) ",
     "legendFormat": "{{pod}}:****:{{reason}}"
    }
   ]
  },
  {
   "title": "NODE memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "BYtes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",container!=\"\",service!=\"prometheus-prometheus-oper-kubelet\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU USAGE IN NODES",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",pod!=\"\",service=\"prometheus-prometheus-oper-kubelet\"}[5m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum  (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", namespace=\"$namespace\",service!=\"prometheus-prometheus-oper-kubelet\"}) by (persistentvolumeclaim) ",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
    }
   ]
  },
  {
   "title": "Network Inputs in the pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Outputs from the pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization graph of Selected Namespace pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\"} [5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Table Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=\"$node\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", node=\"$node\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=\"$node\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{node=\"$node\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", node=\"$node\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=\"$node\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{node=\"$node\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_rss{cluster=\"$cluster\", node=\"$node\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_cache{cluster=\"$cluster\", node=\"$node\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_swap{cluster=\"$cluster\", node=\"$node\",container!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Table Cpu Resources Usage",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", node=\"$node\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", node=\"$node\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", node=\"$node\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", node=\"$node\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", node=\"$node\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", node=\"$node\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", node=\"$node\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Utilization graph of Selected Namespace pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum  (container_memory_usage_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Alert pushing panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "checking pods status",
   "type": "graph",
   "description": "if errors detected it will push notification in slack channel ie. grafana-juicer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_waiting ) by (namespace,pod)"
    }
   ]
  },
  {
   "title": "checking node status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_node_spec_unschedulable) by (node)"
    }
   ]
  },
  { "title": "NODE INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Available Nodes",
   "type": "gauge",
   "description": "Total no of availablele node along with master.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum (kube_node_info)" }
   ]
  },
  {
   "title": "Unavailable nodes",
   "type": "gauge",
   "description": " nodes will be here is there is problem in node",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_spec_unschedulable)"
    }
   ]
  },
  { "title": "CONTAINERS & PODS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Error running pod ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace )(kube_pod_container_status_waiting )",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total pods runnig in each namespace",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_container_status_running)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "CPU , MEMORY & FILESYSTEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Total cpu usage in percentile",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total[1m]) ) / sum (node:node_num_cpu:sum) * 100"
    }
   ]
  },
  {
   "title": "Total memory usage in percentile",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (namespace:container_memory_usage_bytes:sum) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Total cup uitlization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 1, "y": 127 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total[1m]) )"
    }
   ]
  },
  {
   "title": "Total cup ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 127 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (node:node_num_cpu:sum)" }
   ]
  },
  {
   "title": "Total memory uitlization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 127 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (namespace:container_memory_usage_bytes:sum)"
    }
   ]
  },
  {
   "title": "Total Memory ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 127 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum (machine_memory_bytes)" }
   ]
  },
  {
   "title": "Total filesystem utilized percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 130 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (instance:node_filesystem_usage:sum) / sum (node_filesystem_size_bytes) * 100"
    }
   ]
  },
  {
   "title": "Total  filesystem uitlization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 136 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (instance:node_filesystem_usage:sum)"
    }
   ]
  },
  {
   "title": "Total filesystem space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 136 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum  (node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "NODES DISK USAGE ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum (node_filesystem_size_bytes) by (instance) ",
     "legendFormat": "ip-{{instance}}-us-east-2.compute.internal"
    },
    {
     "expr": "sum (node_filesystem_avail_bytes) by (instance) ",
     "legendFormat": "ip-{{instance}}-us-east-2.compute.internal"
    },
    {
     "expr": "sum (node_filesystem_size_bytes) by (instance) - sum (node_filesystem_avail_bytes) by (instance) ",
     "legendFormat": "ip-{{instance}}-us-east-2.compute.internal"
    }
   ]
  }
 ]
}